name: MSRV Check

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'src/**'
      - '.github/workflows/msrv.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'src/**'
      - '.github/workflows/msrv.yml'
  workflow_dispatch:

jobs:
  msrv:
    name: Check MSRV (1.73.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Install Rust 1.73.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.73.0"
      
      - name: Cache cargo registry and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-msrv-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-msrv-
      
      - name: Check compilation
        run: cargo check --all-features
      
      - name: Run tests
        run: cargo test --all-features